name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0,12 * * *'
jobs:
  buildtvstrem:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: download tv files
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: build channel stream 
        run: |
          chmod +x ./script/download.sh
          npm run download
          npm run handler
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/data
          ls ${{ github.workspace }}/output
      - name: deploy iptv stream
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: mark420524/iptvapi
          branch: gh-pages
          folder: output
          token: ${{ secrets.DEPLOY_TOKEN }}
          git-config-name: iptvapi-bot[bot]
          git-config-email: markjava@foxmail.com
          commit-message: '[Bot] deploy to mark420524/iptvapi'
          clean: false
      - run: echo "🍏 This job's status is ${{ job.status }}."
