name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0,12 * * *'
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
      - uses: actions/checkout@v3
      - name: download tv files
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm run download
      - run: npm run handler

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}/data
          ls ${{ github.workspace }}/output
      - run: echo "🍏 This job's status is ${{ job.status }}."
